version: '3'

services:
  linto-wake-me-up:
    build: .
    container_name: linto-wake-me-up
    image: linto/wake-me-up
    depends_on:
      - mongo
      - redis
    ports:
      - 127.0.0.1:8080:3003
    env_file: .docker_env
    volumes:
      - ${HOME}/linto-wake-me-up-records:/usr/src/wake-me-up/webserver/uploads
    networks:
     - internal
  mongo:
    container_name: linto_wakemeup_mongo
    image: mongo:latest
    restart: always
    volumes:
      - ${HOME}/linto-wake-me-up-dbdata:/data/db
      - ./mongodb/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: wakemeup
    networks:
     - internal
  redis:
    container_name: linto_wakemeup_redis
    image: redis:latest
    networks:
      - internal
networks:
  internal: