version: '3'

services:
  linto-wake-me-up:
    build: .
    image: linto-ai/wakemeup
    ports:
      - 127.0.0.1:8080:3003
    env_file: .docker_env
    volumes:
      - ${HOME}/linto-wake-me-up-records:/usr/src/wake-me-up/webserver/uploads
    networks:
     - internal
networks:
  internal: